engines:
    phpmd:
        enabled: true
        config:
          file_extensions: "php"
          rulesets: "cleancode,codesize,design,naming,unusedcode"
ratings:
    paths:
        - "**.css"
        - "**.php"
